remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme

title: Piyush Sharma

description: I am looking for Data Scientist/Data Analyst opportunities.

logo: /assets/img/headshot_circle.png

show_downloads: true

