remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme

title: Piyush Sharma

description: I am looking for Software Development opportunities.

logo: /assets/img/profile_circle.png
